version: '3.8'

services:
  app:
    image: zuaaar/marblow-app:v3
    container_name: marblow-app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    networks:
      - marblow-network

networks:
  marblow-network:
    driver: bridge